apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./

configMapGenerator:
  - name: traefik-values
    namespace: traefik
    files:
      - values.yaml

generatorOptions:
  disableNameSuffixHash: true
